apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: cka-wp
spec:
  replicas: 0
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:6.8-php8.4-apache
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "1000m"
            memory: "4000Mi"
          limits:
            cpu: "2000m"
            memory: "6000Mi"
        env:
        - name: WORDPRESS_DB_HOST
          value: "mysql"
        - name: WORDPRESS_DB_PASSWORD
          value: "example"


