apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-2g-pv
  namespace: cka-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/mysql
