apiVersion: v1
kind: Pod
metadata:
  name: legacy-app
  namespace: cka-sidecar
spec:
  volumes:
    - name: logs
      emptyDir: {}
  containers:
    - name: legacy
      image: busybox
      command:
        [
          "sh",
          "-c",
          "while true; do echo $(date) Legacy log entry >> /var/log/app.log; sleep 5; done",
        ]
      volumeMounts:
        - name: logs
          mountPath: /var/log
