apiVersion: v1
kind: Namespace
metadata:
  name: cka-priority

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: cka-priority
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deployment
  namespace: cka-priority
  labels:
    app: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
        - name: busybox
          image: busybox:1-uclibc
          command:
            [
              "/bin/sh",
              "-c",
              "echo 'Message Hello!' && sleep 3600 && echo 'See you later, Aligator'",
            ]
