apiVersion: v1
kind: Namespace
metadata:
  name: cka-local-path
  labels:
    name: cka-local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-path-pvc
  namespace: cka-local-path
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
